#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Inject DOCX format section content into framework JSON.

Reads a framework.json + DOCX source file, matches framework node titles
against the format section elements, and injects source content (paragraphs
+ tables with precise formatting) into matched nodes.

Usage:
    python cli_inject.py <docx_file> <framework.json> <output.json> [section_keyword]

    docx_file:        original DOCX tender document
    framework.json:   framework generated by LLM (Step 5 output)
    output.json:      output framework with injected elements
    section_keyword:   (optional) keyword to locate format section start

Examples:
    python cli_inject.py tender.docx framework.json framework_injected.json
    python cli_inject.py tender.docx framework.json framework_injected.json "电子投标文件格式"
"""
import sys
import os
import json
import re
from typing import List, Dict, Optional

if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

sys.path.insert(0, os.path.dirname(__file__))
from src.document_parser import DocumentParser


def normalize_title(title: str) -> str:
    """Strip [CENTER]/[RIGHT] markers."""
    t = title.strip()
    for prefix in ('[CENTER]', '[RIGHT]'):
        if t.startswith(prefix):
            t = t[len(prefix):]
    return t.strip()


def find_title_in_elements(title: str, elements: List[Dict]) -> Optional[int]:
    """Find best matching paragraph position for a title in the element list."""
    title_core = re.sub(
        r'^[一二三四五六七八九十百千\d]+([-—][一二三四五六七八九十百千\d]+)*\s*[、.．:：\s]\s*',
        '', title
    ).strip()
    title_no_format = re.sub(r'^格式', '', title).strip()
    title_core_no_format = re.sub(r'^格式', '', title_core).strip()

    best_idx = None
    best_score = 0

    for i, elem in enumerate(elements):
        if elem.get("type") != "para":
            continue
        text = elem.get("text", "").strip()
        if not text:
            continue

        is_bold = elem.get("bold", False)
        bold_bonus = 10 if is_bold else 0

        if text == title or text == title_no_format:
            score = 30 + bold_bonus
            if score > best_score:
                best_score = score
                best_idx = i
            if is_bold:
                return i
            continue

        text_core = re.sub(
            r'^[一二三四五六七八九十百千\d]+([-—][一二三四五六七八九十百千\d]+)*\s*[、.．:：\s]\s*',
            '', text
        ).strip()
        text_core = re.sub(r'^格式', '', text_core).strip()

        if text_core and title_core_no_format:
            if text_core == title_core_no_format:
                score = 20 + bold_bonus
                if score > best_score:
                    best_score = score
                    best_idx = i
            # Containment match: pick the shorter string to check its length (min 2 chars to avoid false positives)
            elif len(min(text_core, title_core_no_format, key=len)) >= 2 and (
                title_core_no_format in text_core or text_core in title_core_no_format
            ):
                score = 10 + bold_bonus
                if score > best_score:
                    best_score = score
                    best_idx = i

    return best_idx


def collect_leaf_nodes(nodes: List[Dict], result: List):
    """DFS collect leaf nodes (no children or empty children)."""
    for node in nodes:
        children = node.get("children", [])
        if children:
            collect_leaf_nodes(children, result)
        else:
            result.append(node)


def collect_all_nodes_for_boundaries(nodes: List[Dict], result: List):
    """DFS collect ALL nodes (including free_form) for boundary detection."""
    for node in nodes:
        result.append(node)
        children = node.get("children", [])
        if children:
            collect_all_nodes_for_boundaries(children, result)


def inject(framework_data: Dict, elements: List[Dict]) -> Dict:
    """Inject elements into framework nodes. Returns modified framework_data dict."""
    nodes = framework_data.get("framework", [])

    # Collect ALL nodes for boundary positions (parents + leaves + free_form)
    all_nodes = []
    collect_all_nodes_for_boundaries(nodes, all_nodes)

    # Collect leaf nodes only (these receive injected elements)
    leaves = []
    collect_leaf_nodes(nodes, leaves)
    leaf_set = set(id(n) for n in leaves if not n.get("is_free_form", False))

    if not all_nodes:
        return 0

    # Find positions for ALL node titles as boundaries (including free_form)
    all_positions = []
    for node in all_nodes:
        title = normalize_title(node.get("title", ""))
        if not title:
            continue
        idx = find_title_in_elements(title, elements)
        if idx is not None:
            # Mark if this is a non-free_form leaf (eligible for injection)
            is_injectable_leaf = (id(node) in leaf_set and not node.get("is_free_form", False))
            all_positions.append((node, idx, is_injectable_leaf))

    if not all_positions:
        return 0

    all_positions.sort(key=lambda x: x[1])

    # Only inject into leaf nodes, but use all positions as boundaries
    injected = 0
    for i, (node, start_idx, is_injectable_leaf) in enumerate(all_positions):
        if not is_injectable_leaf:
            continue  # boundaries only, don't inject
        end_idx = all_positions[i + 1][1] if i + 1 < len(all_positions) else len(elements)
        content_elements = elements[start_idx + 1 : end_idx]
        if content_elements:
            node["elements"] = content_elements
            injected += 1

    framework_data["_injected_count"] = injected
    return framework_data


def main():
    if len(sys.argv) < 4:
        print("Usage: cli_inject.py <docx_file> <framework.json> <output.json> [section_keyword]")
        sys.exit(1)

    docx_file = sys.argv[1]
    framework_path = sys.argv[2]
    output_path = sys.argv[3]
    keyword = sys.argv[4] if len(sys.argv) > 4 else None

    # Extract elements from DOCX
    parser = DocumentParser(docx_file)
    elements = parser.extract_format_section_elements(start_keyword=keyword)
    if not elements:
        print("No format section elements found, output unchanged")
        # Copy input to output
        with open(framework_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        sys.exit(0)

    para_count = sum(1 for e in elements if e["type"] == "para")
    table_count = sum(1 for e in elements if e["type"] == "table")
    print(f"Extracted {len(elements)} elements ({para_count} paragraphs, {table_count} tables)")

    # Load framework
    with open(framework_path, "r", encoding="utf-8") as f:
        framework_data = json.load(f)

    # Inject
    framework_data = inject(framework_data, elements)
    injected = framework_data.pop("_injected_count", 0)
    print(f"Injected: {injected} nodes")

    # Save
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(framework_data, f, ensure_ascii=False, indent=2)
    print(f"Output: {output_path}")


if __name__ == "__main__":
    main()
